use_frameworks!

platform :ios, '10.0'

target 'ABTastyOpenfeature-iOS_Example' do
  pod 'ABTastyOpenfeature-iOS', :path => '../'

  target 'ABTastyOpenfeature-iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
