use_frameworks!

platform :ios, '15.0'

target 'ABTastyOpenfeature-iOS_Example' do
  pod 'ABTastyOpenfeature-iOS', :path => '../'

  target 'ABTastyOpenfeature-iOS_Tests' do
    inherit! :search_paths

   
  end
end
